// src/jobs/definitions.ts
import { WindsorEndpoint } from '../shared/vendors/windsor/windsor.d';

// =================================================================
// ─── CORE HELPER TYPES ───────────────────────────────────────────
// =================================================================

/** Represents a table in BigQuery. */
export type BigQueryTable = {
	readonly dataset: string;
	readonly table: string;
};

// =================================================================
// ─── 1. IMPORTS (BRONZE LAYER) ───────────────────────────────────
// =================================================================

/** The minimal, declarative shape for a Windsor import definition. */
export type WindsorImportDef<E extends WindsorEndpoint> = {
	readonly id: string; // e.g., 'coreKeywordPerformance'
	readonly platform: string; // e.g., 'google_ads'
	readonly endpoint: E;
	readonly description: string;

	// Request parameters
	readonly metrics: ReadonlyArray<string>;
	readonly dimensions: ReadonlyArray<string>;
	readonly datePreset: string; // e.g., 'last_90d'
	readonly params?: Record<string, any>;

	// Destination parameters
	readonly version: number;
	readonly partitionBy: string;
	readonly clusterBy?: ReadonlyArray<string>;
};

/** The fully hydrated, runtime representation of a Windsor import. */
export type WindsorImport<E extends WindsorEndpoint = WindsorEndpoint> =
	WindsorImportDef<E> & {
		readonly connector: 'windsor';
		readonly destinationTable: BigQueryTable; // Derived
		readonly request: {
			// Derived
			readonly endpoint: E;
			readonly metrics: ReadonlyArray<string>;
			readonly dimensions: ReadonlyArray<string>;
			readonly params: Record<string, any>;
		};
	};

// =================================================================
// ─── 2. ENTITIES (SILVER LAYER) ───────────────────────────────────
// =================================================================

/** A source pointing to a bronze table generated by an import. */
export type EntitySource = {
	readonly import: WindsorImport; // Direct, typed reference
	// We can add other source types later, e.g., another entity
};

/** The minimal, declarative shape for an Entity definition. */
export type EntityDef = {
	readonly id: string; // e.g., 'keywordDaily'
	readonly description: string;
	readonly sources: ReadonlyArray<EntitySource>;
	readonly transformSql: string; // The SQL to create the silver table
	readonly partitionBy?: string;
	readonly clusterBy?: ReadonlyArray<string>;
	// `grain` and `schema` are now derived, not defined.
};

/** The fully hydrated, runtime representation of an Entity. */
export type Entity = Omit<EntityDef, 'sources'> & {
	readonly sourceTables: ReadonlyArray<BigQueryTable>; // Derived from sources
	readonly storage: BigQueryTable; // Derived
	readonly grain: ReadonlyArray<string>; // Derived from SQL GROUP BY
	readonly schema: {
		// Derived from SQL SELECT at runtime
		readonly metrics: Record<string, { type: string }>;
		readonly dimensions: Record<string, { type: string }>;
	};
};

// =================================================================
// ─── 3. SIGNALS (GOLD LAYER) ─────────────────────────────────────
// =================================================================

/** A target pointing to a silver table generated by an entity. */
export type SignalTarget = {
	readonly entity: Entity; // Direct, typed reference
};

/** The minimal, declarative shape for a Signal definition. */
export type SignalDef = {
	readonly id: string; // e.g., 'wastedSpendKeyword'
	readonly kind: 'opportunity' | 'risk' | 'information';
	readonly signalType: 'deterministic' | 'ml';
	readonly description: string;
	readonly target: SignalTarget;
	readonly predicate: string; // e.g., 'spend > 0 AND conversions == 0'

	readonly applicability: {
		readonly minWindowDays: number;
		readonly supportsCustomDateRange: boolean;
		readonly supportsFilteredAccounts: boolean;
		readonly requiresFullAccountContext: boolean;
	};

	readonly output: {
		readonly keyFields: ReadonlyArray<string>;
		readonly impact: {
			readonly formula: string;
			readonly unit: 'currency' | 'count' | 'percentage';
			readonly direction: 'positive_if_fixed' | 'negative_if_fixed';
		};
		readonly confidence: {
			readonly mode: 'fixed' | 'dynamic';
			readonly value: number;
		};
	};

	readonly snapshot: {
		readonly enabled: boolean;
		readonly cadence: 'daily' | 'weekly' | 'monthly' | 'onRun';
		readonly windowId: string;
		readonly attributionKey: ReadonlyArray<string>;
		readonly metrics: Record<
			string,
			{ field: string; aggregate: 'sum' | 'avg' | 'max' | 'min' | 'count' }
		>;
		readonly trackDelta: boolean;
	};

	readonly presentation: {
		readonly titleTemplate: string;
		readonly summaryTemplate: string;
		readonly tags: ReadonlyArray<string>;
		readonly llmExplainPrompt?: string;
		readonly suggestedUserPrompts?: ReadonlyArray<string>;
	};
};

/** The fully hydrated, runtime representation of a Signal. */
export type Signal = SignalDef & {
	readonly goldTable: BigQueryTable; // Derived
};
